export const COUNTRIES = [
  'Afghanistan','Albania','Algeria','Andorra','Angola','Antigua and Barbuda','Argentina','Armenia','Australia','Austria',
  'Azerbaijan','Bahamas','Bahrain','Bangladesh','Barbados','Belarus','Belgium','Belize','Benin','Bhutan',
  'Bolivia','Bosnia and Herzegovina','Botswana','Brazil','Brunei','Bulgaria','Burkina Faso','Burundi','Cabo Verde','Cambodia',
  'Cameroon','Canada','Central African Republic','Chad','Chile','China','Colombia','Comoros','Congo (Republic)','Congo (Democratic Republic)',
  'Costa Rica','Croatia','Cuba','Cyprus','Czech Republic','Denmark','Djibouti','Dominica','Dominican Republic','Ecuador',
  'Egypt','El Salvador','Equatorial Guinea','Eritrea','Estonia','Eswatini','Ethiopia','Fiji','Finland','France',
  'Gabon','Gambia','Georgia','Germany','Ghana','Greece','Grenada','Guatemala','Guinea','Guinea-Bissau',
  'Guyana','Haiti','Honduras','Hungary','Iceland','India','Indonesia','Iran','Iraq','Ireland',
  'Israel','Italy','Jamaica','Japan','Jordan','Kazakhstan','Kenya','Kiribati','Kosovo','Kuwait',
  'Kyrgyzstan','Laos','Latvia','Lebanon','Lesotho','Liberia','Libya','Liechtenstein','Lithuania','Luxembourg',
  'Madagascar','Malawi','Malaysia','Maldives','Mali','Malta','Marshall Islands','Mauritania','Mauritius','Mexico',
  'Micronesia','Moldova','Monaco','Mongolia','Montenegro','Morocco','Mozambique','Myanmar','Namibia','Nauru',
  'Nepal','Netherlands','New Zealand','Nicaragua','Niger','Nigeria','North Korea','North Macedonia','Norway','Oman',
  'Pakistan','Palau','Palestine','Panama','Papua New Guinea','Paraguay','Peru','Philippines','Poland','Portugal',
  'Qatar','Romania','Russia','Rwanda','Saint Kitts and Nevis','Saint Lucia','Saint Vincent and the Grenadines','Samoa','San Marino','São Tomé and Príncipe',
  'Saudi Arabia','Senegal','Serbia','Seychelles','Sierra Leone','Singapore','Slovakia','Slovenia','Solomon Islands','Somalia',
  'South Africa','South Korea','South Sudan','Spain','Sri Lanka','Sudan','Suriname','Sweden','Switzerland','Syria',
  'Taiwan','Tajikistan','Tanzania','Thailand','Timor-Leste','Togo','Tonga','Trinidad and Tobago','Tunisia','Turkey',
  'Turkmenistan','Tuvalu','Uganda','Ukraine','United Arab Emirates','United Kingdom','United States','Uruguay','Uzbekistan','Vanuatu',
  'Vatican City','Venezuela','Vietnam','Yemen','Zambia','Zimbabwe',
]

export const SECTORS = [
  'Education','Health','Community Development','Youth Empowerment','Technology & IT','Agriculture',
  'Environment & Climate','Governance & Public Policy','Arts & Culture','Sports & Recreation','Human Rights',
  'Gender Equality','Economic Development','Social Innovation','Infrastructure','Water & Sanitation',
  'Humanitarian Aid','Research & Academia','Media & Communications','Finance & Banking','Insurance',
  'Legal & Justice','Energy & Utilities','Housing & Urban Development','Food Security & Nutrition',
  'Disability & Inclusion','Migration & Refugees','Peace & Conflict Resolution','Tourism & Hospitality',
  'Manufacturing','Transportation & Logistics','Telecommunications','Retail & Commerce','Real Estate',
  'Construction','Mining & Natural Resources','Pharmaceuticals & Biotechnology','Automotive',
  'Aerospace & Defense','Consulting & Professional Services','Advertising & Marketing','Fashion & Textiles',
  'Entertainment & Media','Hospitality & Food Services','Cybersecurity','Blockchain & Web3',
  'Artificial Intelligence','E-commerce','Supply Chain & Procurement','Nonprofit Management',
  'Religious & Faith-Based','Other',
]

// Display labels shown to French-language visitors. The underlying value stored in form
// state and submitted to the API/emails always stays the canonical English string above,
// so admin-facing data remains consistent regardless of the visitor's chosen language.
export const COUNTRY_LABELS_FR: Record<string, string> = {
  'Afghanistan': 'Afghanistan', 'Albania': 'Albanie', 'Algeria': 'Algérie', 'Andorra': 'Andorre', 'Angola': 'Angola',
  'Antigua and Barbuda': 'Antigua-et-Barbuda', 'Argentina': 'Argentine', 'Armenia': 'Arménie', 'Australia': 'Australie', 'Austria': 'Autriche',
  'Azerbaijan': 'Azerbaïdjan', 'Bahamas': 'Bahamas', 'Bahrain': 'Bahreïn', 'Bangladesh': 'Bangladesh', 'Barbados': 'Barbade',
  'Belarus': 'Biélorussie', 'Belgium': 'Belgique', 'Belize': 'Belize', 'Benin': 'Bénin', 'Bhutan': 'Bhoutan',
  'Bolivia': 'Bolivie', 'Bosnia and Herzegovina': 'Bosnie-Herzégovine', 'Botswana': 'Botswana', 'Brazil': 'Brésil', 'Brunei': 'Brunei',
  'Bulgaria': 'Bulgarie', 'Burkina Faso': 'Burkina Faso', 'Burundi': 'Burundi', 'Cabo Verde': 'Cap-Vert', 'Cambodia': 'Cambodge',
  'Cameroon': 'Cameroun', 'Canada': 'Canada', 'Central African Republic': 'République centrafricaine', 'Chad': 'Tchad', 'Chile': 'Chili',
  'China': 'Chine', 'Colombia': 'Colombie', 'Comoros': 'Comores', 'Congo (Republic)': 'Congo (République du)', 'Congo (Democratic Republic)': 'Congo (République démocratique du)',
  'Costa Rica': 'Costa Rica', 'Croatia': 'Croatie', 'Cuba': 'Cuba', 'Cyprus': 'Chypre', 'Czech Republic': 'République tchèque',
  'Denmark': 'Danemark', 'Djibouti': 'Djibouti', 'Dominica': 'Dominique', 'Dominican Republic': 'République dominicaine', 'Ecuador': 'Équateur',
  'Egypt': 'Égypte', 'El Salvador': 'Salvador', 'Equatorial Guinea': 'Guinée équatoriale', 'Eritrea': 'Érythrée', 'Estonia': 'Estonie',
  'Eswatini': 'Eswatini', 'Ethiopia': 'Éthiopie', 'Fiji': 'Fidji', 'Finland': 'Finlande', 'France': 'France',
  'Gabon': 'Gabon', 'Gambia': 'Gambie', 'Georgia': 'Géorgie', 'Germany': 'Allemagne', 'Ghana': 'Ghana',
  'Greece': 'Grèce', 'Grenada': 'Grenade', 'Guatemala': 'Guatemala', 'Guinea': 'Guinée', 'Guinea-Bissau': 'Guinée-Bissau',
  'Guyana': 'Guyana', 'Haiti': 'Haïti', 'Honduras': 'Honduras', 'Hungary': 'Hongrie', 'Iceland': 'Islande',
  'India': 'Inde', 'Indonesia': 'Indonésie', 'Iran': 'Iran', 'Iraq': 'Irak', 'Ireland': 'Irlande',
  'Israel': 'Israël', 'Italy': 'Italie', 'Jamaica': 'Jamaïque', 'Japan': 'Japon', 'Jordan': 'Jordanie',
  'Kazakhstan': 'Kazakhstan', 'Kenya': 'Kenya', 'Kiribati': 'Kiribati', 'Kosovo': 'Kosovo', 'Kuwait': 'Koweït',
  'Kyrgyzstan': 'Kirghizistan', 'Laos': 'Laos', 'Latvia': 'Lettonie', 'Lebanon': 'Liban', 'Lesotho': 'Lesotho',
  'Liberia': 'Liberia', 'Libya': 'Libye', 'Liechtenstein': 'Liechtenstein', 'Lithuania': 'Lituanie', 'Luxembourg': 'Luxembourg',
  'Madagascar': 'Madagascar', 'Malawi': 'Malawi', 'Malaysia': 'Malaisie', 'Maldives': 'Maldives', 'Mali': 'Mali',
  'Malta': 'Malte', 'Marshall Islands': 'Îles Marshall', 'Mauritania': 'Mauritanie', 'Mauritius': 'Maurice', 'Mexico': 'Mexique',
  'Micronesia': 'Micronésie', 'Moldova': 'Moldavie', 'Monaco': 'Monaco', 'Mongolia': 'Mongolie', 'Montenegro': 'Monténégro',
  'Morocco': 'Maroc', 'Mozambique': 'Mozambique', 'Myanmar': 'Myanmar', 'Namibia': 'Namibie', 'Nauru': 'Nauru',
  'Nepal': 'Népal', 'Netherlands': 'Pays-Bas', 'New Zealand': 'Nouvelle-Zélande', 'Nicaragua': 'Nicaragua', 'Niger': 'Niger',
  'Nigeria': 'Nigeria', 'North Korea': 'Corée du Nord', 'North Macedonia': 'Macédoine du Nord', 'Norway': 'Norvège', 'Oman': 'Oman',
  'Pakistan': 'Pakistan', 'Palau': 'Palaos', 'Palestine': 'Palestine', 'Panama': 'Panama', 'Papua New Guinea': 'Papouasie-Nouvelle-Guinée',
  'Paraguay': 'Paraguay', 'Peru': 'Pérou', 'Philippines': 'Philippines', 'Poland': 'Pologne', 'Portugal': 'Portugal',
  'Qatar': 'Qatar', 'Romania': 'Roumanie', 'Russia': 'Russie', 'Rwanda': 'Rwanda', 'Saint Kitts and Nevis': 'Saint-Kitts-et-Nevis',
  'Saint Lucia': 'Sainte-Lucie', 'Saint Vincent and the Grenadines': 'Saint-Vincent-et-les-Grenadines', 'Samoa': 'Samoa', 'San Marino': 'Saint-Marin', 'São Tomé and Príncipe': 'Sao Tomé-et-Principe',
  'Saudi Arabia': 'Arabie saoudite', 'Senegal': 'Sénégal', 'Serbia': 'Serbie', 'Seychelles': 'Seychelles', 'Sierra Leone': 'Sierra Leone',
  'Singapore': 'Singapour', 'Slovakia': 'Slovaquie', 'Slovenia': 'Slovénie', 'Solomon Islands': 'Îles Salomon', 'Somalia': 'Somalie',
  'South Africa': 'Afrique du Sud', 'South Korea': 'Corée du Sud', 'South Sudan': 'Soudan du Sud', 'Spain': 'Espagne', 'Sri Lanka': 'Sri Lanka',
  'Sudan': 'Soudan', 'Suriname': 'Suriname', 'Sweden': 'Suède', 'Switzerland': 'Suisse', 'Syria': 'Syrie',
  'Taiwan': 'Taïwan', 'Tajikistan': 'Tadjikistan', 'Tanzania': 'Tanzanie', 'Thailand': 'Thaïlande', 'Timor-Leste': 'Timor oriental',
  'Togo': 'Togo', 'Tonga': 'Tonga', 'Trinidad and Tobago': 'Trinité-et-Tobago', 'Tunisia': 'Tunisie', 'Turkey': 'Turquie',
  'Turkmenistan': 'Turkménistan', 'Tuvalu': 'Tuvalu', 'Uganda': 'Ouganda', 'Ukraine': 'Ukraine', 'United Arab Emirates': 'Émirats arabes unis',
  'United Kingdom': 'Royaume-Uni', 'United States': 'États-Unis', 'Uruguay': 'Uruguay', 'Uzbekistan': 'Ouzbékistan', 'Vanuatu': 'Vanuatu',
  'Vatican City': 'Cité du Vatican', 'Venezuela': 'Venezuela', 'Vietnam': 'Viêt Nam', 'Yemen': 'Yémen', 'Zambia': 'Zambie',
  'Zimbabwe': 'Zimbabwe',
}

export const SECTOR_LABELS_FR: Record<string, string> = {
  'Education': 'Éducation',
  'Health': 'Santé',
  'Community Development': 'Développement communautaire',
  'Youth Empowerment': 'Autonomisation des jeunes',
  'Technology & IT': 'Technologie et informatique',
  'Agriculture': 'Agriculture',
  'Environment & Climate': 'Environnement et climat',
  'Governance & Public Policy': 'Gouvernance et politiques publiques',
  'Arts & Culture': 'Arts et culture',
  'Sports & Recreation': 'Sport et loisirs',
  'Human Rights': 'Droits humains',
  'Gender Equality': 'Égalité des genres',
  'Economic Development': 'Développement économique',
  'Social Innovation': 'Innovation sociale',
  'Infrastructure': 'Infrastructures',
  'Water & Sanitation': 'Eau et assainissement',
  'Humanitarian Aid': 'Aide humanitaire',
  'Research & Academia': 'Recherche et milieu universitaire',
  'Media & Communications': 'Médias et communication',
  'Finance & Banking': 'Finance et banque',
  'Insurance': 'Assurance',
  'Legal & Justice': 'Droit et justice',
  'Energy & Utilities': 'Énergie et services publics',
  'Housing & Urban Development': 'Logement et développement urbain',
  'Food Security & Nutrition': 'Sécurité alimentaire et nutrition',
  'Disability & Inclusion': 'Handicap et inclusion',
  'Migration & Refugees': 'Migration et réfugiés',
  'Peace & Conflict Resolution': 'Paix et résolution des conflits',
  'Tourism & Hospitality': 'Tourisme et hôtellerie',
  'Manufacturing': 'Industrie manufacturière',
  'Transportation & Logistics': 'Transport et logistique',
  'Telecommunications': 'Télécommunications',
  'Retail & Commerce': 'Commerce de détail',
  'Real Estate': 'Immobilier',
  'Construction': 'Construction',
  'Mining & Natural Resources': 'Mines et ressources naturelles',
  'Pharmaceuticals & Biotechnology': 'Pharmacie et biotechnologie',
  'Automotive': 'Automobile',
  'Aerospace & Defense': 'Aérospatiale et défense',
  'Consulting & Professional Services': 'Conseil et services professionnels',
  'Advertising & Marketing': 'Publicité et marketing',
  'Fashion & Textiles': 'Mode et textile',
  'Entertainment & Media': 'Divertissement et médias',
  'Hospitality & Food Services': 'Hôtellerie et restauration',
  'Cybersecurity': 'Cybersécurité',
  'Blockchain & Web3': 'Blockchain et Web3',
  'Artificial Intelligence': 'Intelligence artificielle',
  'E-commerce': 'Commerce électronique',
  'Supply Chain & Procurement': "Chaîne d'approvisionnement et achats",
  'Nonprofit Management': "Gestion d'organisations à but non lucratif",
  'Religious & Faith-Based': 'Religieux et confessionnel',
  'Other': 'Autre',
}
