export const PEOPLE: Record<string, { name: string; role: string; roleFr?: string; bio: string | string[]; bioFr?: string | string[]; linkedin?: string; image?: string; imagePosition?: string }> = {
  'daryll-giovanny-bikak-mbal': {
    name: 'Giovanny Bikak Mbal',
    role: 'Chair, Board Member',
    roleFr: 'Président du Conseil d\'administration',
    bio: [
      "Giovanny is Chair of the Board of Directors and Interim Executive Director of Gwags Global Impact Institution. He sets the institution's strategic direction, oversees its governance, and has led its development from a student-led initiative in Douala, Cameroon, into an internationally incorporated institution operating across multiple sectors.",
      "Under his leadership, Gwags incorporated as a nonprofit in both the United States and Cameroon, developed and launched its portfolio of programs, forged partnerships across sectors, and transitioned from the Gwags Foundation to Gwags Global Impact Institution. He has also overseen the development of the institution's digital infrastructure.",
      "His professional and academic experience reflects a similar range. He works as a Software Developer at Ciena and has held roles in technical project management at Carleton Blueprint, where he managed development teams building software for nonprofits. At Carleton University, he has served as an Undergraduate Teaching Assistant for Computer Science courses, a Research Assistant investigating adaptive attack strategies in reinforcement learning, and a Workshop Facilitator in introductory economics.",
      "His work across these roles reflects a consistent interest in how technology, institutional design, and governance can be leveraged to address systemic barriers to opportunity. This perspective extends beyond Gwags and underpins a deeper commitment to public service and national development, with the conviction that the transformation of nations begins with the strength of their institutions and the investment in their people. Originally from Douala, Cameroon, Giovanny intends to return to serve.",
    ],
    bioFr: [
      "Giovanny est Président du Conseil d'administration et Directeur Exécutif par intérim de Gwags Global Impact Institution. Il définit l'orientation stratégique de l'institution, supervise sa gouvernance et a conduit son évolution depuis une initiative étudiante à Douala, au Cameroun, jusqu'à une institution incorporée à l'international intervenant dans plusieurs secteurs.",
      "Sous sa direction, Gwags s'est constituée en organisme à but non lucratif aux États-Unis et au Cameroun, a développé et déployé son portefeuille de programmes, tissé des partenariats intersectoriels et mené à bien sa transformation institutionnelle, passant de la Fondation Gwags à Gwags Global Impact Institution. Il a également piloté le développement de l'infrastructure numérique de l'institution.",
      "Son parcours professionnel et académique s'inscrit dans la même diversité. Il exerce en tant que développeur logiciel chez Ciena et a assumé des responsabilités en gestion de projets techniques à Carleton Blueprint, où il a encadré des équipes de développement au service d'organismes à but non lucratif. À l'Université Carleton, il a été assistant d'enseignement pour des cours d'informatique, assistant de recherche sur les stratégies d'attaque adaptatives en apprentissage par renforcement, et animateur d'ateliers en économie.",
      "L'ensemble de ce parcours traduit un intérêt soutenu pour la manière dont la technologie, l'architecture institutionnelle et la gouvernance peuvent contribuer à lever les obstacles systémiques à l'accès aux opportunités. Cette conviction dépasse le cadre de Gwags et nourrit un engagement profond envers le service public et le développement des nations, fondé sur l'idée que leur transformation passe par la solidité de leurs institutions et l'investissement dans leurs populations. Originaire de Douala, au Cameroun, Giovanny compte y retourner pour servir.",
    ],
    linkedin: 'https://www.linkedin.com/in/giovannybikakmbal/',
    image: '/images/leadership/giovanny-bikak-mbal.jpg',
  },
  'vianney-tanifor': {
    name: 'Vianney Tanifor',
    role: 'Board Member',
    roleFr: "Membre du Conseil d'Administration",
    bio: [
      "Vianney Tanifor serves on the Governance Board of Gwags Global Impact Institution, where he leads the Audit & Finance Committee. His work is shaped by a broader commitment to medicine, public health, research, and public policy, with a particular interest in strengthening healthcare systems and advancing sustainable development in Cameroon. Through Gwags, he has worked across institutional governance, health initiatives, program implementation, and partnerships aimed at expanding opportunities and improving community well-being.",
      "Vianney studies Biological Sciences and Political Science at the University of Maryland, Baltimore County, where his academic and research experiences have deepened his interest in the relationship between disease, healthcare delivery, and the policies that shape access to care. He is especially interested in neuroinfectious disease and in how scientific evidence can inform stronger health systems, better policy, and more effective responses to the health challenges facing underserved communities.",
      "His work with Gwags has allowed him to apply these interests directly. During a major health campaign in Cameroon, he participated in surgical care, contributed to project financing and implementation, and helped collect health data that is now being analyzed to better understand disease patterns in the communities served. In Geneva, he presented the work of Gwags and was invited to discuss healthcare challenges in Cameroon. He has also partnered with the World Health Organization to support skills-development workshops for medical students in Cameroon.",
      "Vianney hopes to build a career that bridges medicine, research, public service, and policy. His long-term interests center on contributing to better health outcomes not only through clinical and scientific work, but also through the institutions, policies, and systems that determine how healthcare is delivered and who is able to access it.",
    ],
    bioFr: [
      "Vianney Tanifor siège au Conseil d'Administration de Gwags Global Impact Institution, où il préside le Comité d'Audit et des Finances. Son parcours s'inscrit dans un engagement plus large envers la médecine, la santé publique, la recherche et les politiques publiques, avec un intérêt particulier pour le renforcement des systèmes de santé et le développement durable au Cameroun. Au sein de Gwags, il a contribué à la gouvernance institutionnelle, aux initiatives de santé, à la mise en œuvre de programmes et à des partenariats visant à élargir les opportunités et à améliorer le bien-être des communautés.",
      "Vianney poursuit des études en sciences biologiques et en sciences politiques à l'Université du Maryland, comté de Baltimore, où ses expériences académiques et de recherche ont approfondi son intérêt pour les liens entre la maladie, la prestation des soins de santé et les politiques qui déterminent l'accès aux soins. Il s'intéresse particulièrement aux maladies neuro-infectieuses et à la manière dont les données scientifiques peuvent contribuer à des systèmes de santé plus solides, de meilleures politiques et des réponses plus efficaces aux défis sanitaires auxquels font face les communautés défavorisées.",
      "Son engagement au sein de Gwags lui a permis de mettre ces intérêts en pratique. Lors d'une importante campagne de santé au Cameroun, il a participé aux soins chirurgicaux, contribué au financement et à la mise en œuvre du projet, et aidé à collecter des données sanitaires actuellement en cours d'analyse pour mieux comprendre les tendances épidémiologiques dans les communautés desservies. À Genève, il a présenté les travaux de Gwags et a été invité à discuter des enjeux de santé au Cameroun. Il a également collaboré avec l'Organisation mondiale de la Santé pour soutenir des ateliers de développement des compétences destinés aux étudiants en médecine au Cameroun.",
      "Vianney aspire à bâtir une carrière à la croisée de la médecine, de la recherche, du service public et des politiques publiques. Ses ambitions à long terme portent sur l'amélioration des résultats en matière de santé, non seulement par le travail clinique et scientifique, mais aussi par les institutions, les politiques et les systèmes qui déterminent comment les soins sont dispensés et qui peut y accéder.",
    ],
    linkedin: 'https://www.linkedin.com/in/vianney-tanifor-9a76b0280/',
    image: '/images/leadership/vianney-tanifor.jpg',
  },
  'noa-winner': {
    name: 'Winner Noa',
    role: 'Board Member of Gwags Global Impact Institution',
    roleFr: "Membre du Conseil d'administration de Gwags Global Impact Institution",
    bio: [
      "Winner Noa is a Board Member of Gwags Global Impact Institution and Chair of the Governance, Regulatory & Ethics Committee. In this capacity, he leads the Board's work on governance standards, board composition and effectiveness, ethical oversight, and regulatory alignment across the jurisdictions in which Gwags operates. He also advises on the institutional frameworks required to support the organization's continued growth and development.",
      "Since Gwags' early years, Winner has played an instrumental role in shaping the models that have accompanied the institution's evolution. From its early focus on direct community support, through its shift toward youth empowerment and capacity building, he has contributed to designing approaches that strengthened the sustainability and long-term relevance of its work. As Gwags evolved into a Global Impact Institution, he played a central role in developing its current model of structuring, financing, and accelerating impact beyond its own programs, enabling the institution to strengthen locally rooted organizations and extend impact through them.",
      "Beyond Gwags, Winner leads Cross, a strategic advisory practice through which he works with leaders and organizations on governance, institutional development, corporate structuring, and strategic decision-making. He is also founder and editor-in-chief of Systemic, an independent publication examining the political, economic, and social systems that shape contemporary societies, and serves on the board of Fifty Six, a pan-African intellectual think tank. His broader experience spans law, corporate and institutional strategy, organizational transformation, and work across public and private-sector environments.",
      "Winner's academic background began in management and has progressively expanded into law and international finance, reflecting a broader interest in how institutions are governed, financed, and positioned within increasingly interconnected economic and regulatory systems. Over the long term, he aims to contribute to building and strengthening institutions capable of creating the conditions in which economic initiative, innovation, and social progress can flourish sustainably.",
    ],
    bioFr: [
      "Winner Noa est membre du Conseil d'administration de Gwags Global Impact Institution et préside le Comité de la gouvernance, de la réglementation et de l'éthique. À ce titre, il pilote les travaux du Conseil relatifs aux normes de gouvernance, à la composition et à l'efficacité du Conseil, à la supervision éthique ainsi qu'à l'alignement réglementaire dans l'ensemble des juridictions où Gwags opère. Il contribue également à la définition des cadres institutionnels nécessaires à la croissance et au développement de l'organisation.",
      "Depuis les premières années de Gwags, Winner a joué un rôle déterminant dans la conception des modèles qui ont accompagné l'évolution de l'institution. De ses premières actions de solidarité directe à son orientation vers l'autonomisation des jeunes et le renforcement des capacités, il a contribué à élaborer des approches visant à consolider la pérennité et la pertinence à long terme de son action. Lors de la transformation de Gwags en Global Impact Institution, il a joué un rôle central dans la conception de son modèle actuel, fondé sur la structuration, le financement et l'accélération de l'impact au-delà de ses propres programmes, permettant à l'institution de renforcer des organisations ancrées dans leurs communautés et d'amplifier l'impact à travers elles.",
      "En parallèle de ses fonctions au sein de Gwags, Winner dirige Cross, un cabinet de conseil stratégique à travers lequel il accompagne des dirigeants et des organisations sur des enjeux de gouvernance, de développement institutionnel, de structuration d'organisations et de prise de décision stratégique. Il est également fondateur et rédacteur en chef de Systemic, une publication indépendante consacrée à l'analyse des systèmes politiques, économiques et sociaux qui façonnent les sociétés contemporaines, et siège au conseil d'administration de Fifty Six, un think tank intellectuel panafricain. Son expérience couvre plus largement le droit, la stratégie institutionnelle et d'entreprise, la transformation des organisations ainsi que des environnements relevant des secteurs public et privé.",
      "Sa formation, initialement orientée vers le management, s'est progressivement élargie au droit et à la finance internationale, traduisant un intérêt plus profond pour la manière dont les institutions sont gouvernées, financées et positionnées au sein de systèmes économiques et réglementaires de plus en plus interconnectés. À long terme, Winner entend contribuer à bâtir et renforcer des institutions capables de réunir les conditions nécessaires à l'épanouissement durable de l'initiative économique, de l'innovation et du progrès social.",
    ],
    linkedin: 'https://www.linkedin.com/in/winnernoa/',
    image: '/images/leadership/winner-noa.jpg',
  },
  'placeholder-executive-director': {
    name: '[Name Placeholder]',
    role: 'Executive Director',
    bio: "The Executive Director oversees the day-to-day operations of Gwags, working closely with the governance board to implement the institution's strategic priorities and ensure program delivery.",
    linkedin: 'https://linkedin.com/in/placeholder', // UPDATE: Replace with actual LinkedIn URL
  },
  'placeholder-director-programs': {
    name: '[Name Placeholder]',
    role: 'Director of Programs',
    bio: "The Director of Programs leads the design, delivery, and evaluation of Gwags's active portfolio of initiatives across education, health, and community development.",
    linkedin: 'https://linkedin.com/in/placeholder', // UPDATE: Replace with actual LinkedIn URL
  },
  'placeholder-director-operations': {
    name: 'Shifu Hammadina',
    role: 'Chief Program Officer',
    roleFr: 'Directeur des Programmes',
    bio: "Shifu leads the design, execution, and evaluation of all Gwags programs, translating the institution's strategy into measurable field impact.",
    bioFr: "Shifu dirige la conception, l'exécution et l'évaluation de l'ensemble des programmes de Gwags, traduisant la stratégie de l'institution en impact mesurable sur le terrain.",
    linkedin: 'https://www.linkedin.com/in/shifu-afayi-h-3708412a3/',
    image: '/images/leadership/shifu-hammadina.jpg',
  },
  'placeholder-director-communications': {
    name: 'Ornella Ebolo',
    role: 'Chief Communications Officer',
    roleFr: 'Directrice de la Communication',
    bio: "The Chief Communications Officer leads Gwags's external engagement, institutional communications, and the development of strategic partnerships.",
    image: '/images/leadership/ornella-ebolo.jpg',
    imagePosition: 'center 16%',
  },
  'gloria-asopjio': {
    name: 'Gloria Asopjio',
    role: 'Founding Member',
    bio: "Gloria led community outreach for the organization's early programs.",
    bioFr: "Gloria a coordonné les relations communautaires pour les premières initiatives de l'organisation.",
    linkedin: 'https://www.linkedin.com/in/gloria-alana-asopjio-060012332/',
    image: '/images/leadership/gloria-asopjio.jpg',
  },
  'alissa-mokem': {
    name: 'Alissa Mokem',
    role: 'Founding Member',
    bio: "Alissa managed the organization's financial operations.",
    bioFr: "Alissa a assuré la gestion financière de l'organisation.",
    image: '/images/leadership/alissa-mokem.jpg',
    imagePosition: 'center 26%',
  },
}
