export const PEOPLE: Record<string, { name: string; role: string; roleFr?: string; bio: string | string[]; bioFr?: string | string[]; linkedin?: string; image?: string; imagePosition?: string }> = {
  'daryll-giovanny-bikak-mbal': {
    name: 'Giovanny Bikak Mbal',
    role: 'Chair, Board Member',
    roleFr: 'Président du Conseil d\'administration',
    bio: "As Chair, Giovanny shapes the institution's strategies, advocates for the institution's issues, and sets the organization's overall direction. He also serves as Interim Executive Director.",
    bioFr: "En tant que Président, Giovanny façonne les stratégies de l'institution, défend les causes de l'institution et définit l'orientation générale de l'organisation. Il occupe également le poste de Directeur Exécutif par intérim.",
    linkedin: 'https://www.linkedin.com/in/giovannybikakmbal/',
    image: '/images/leadership/giovanny-bikak-mbal.jpg',
  },
  'vianney-tanifor': {
    name: 'Vianney Tanifor',
    role: 'Board Member',
    roleFr: "Membre du Conseil d'Administration",
    bio: [
      "Vianney Tanifor serves on the Governance Board of Gwags Global Impact Institution, where he leads the Audit & Finance Committee. His work is shaped by a broader commitment to medicine, public health, research, and public policy, with a particular interest in strengthening healthcare systems and advancing sustainable development in Cameroon. Through Gwags, he has worked across institutional governance, health initiatives, program implementation, and partnerships aimed at expanding opportunities and improving community well-being.",
      "Vianney studies Biological Sciences and Political Science at the University of Maryland, Baltimore County, where his academic and research experiences have deepened his interest in the relationship between disease, healthcare delivery, and the policies that shape access to care. He is especially interested in neuroinfectious disease and in how scientific evidence can inform stronger health systems, better policy, and more effective responses to the health challenges facing underserved communities.",
      "His work with Gwags has allowed him to apply these interests directly. During a major health campaign in Cameroon, he participated in surgical care, contributed to project financing and implementation, and helped collect health data that is now being analyzed to better understand disease patterns in the communities served. In Geneva, he presented the work of Gwags and was invited to discuss healthcare challenges in Cameroon. He has also partnered with the World Health Organization to support skills-development workshops for medical students in Cameroon.",
      "Vianney hopes to build a career that bridges medicine, research, public service, and policy. His long-term interests center on contributing to better health outcomes not only through clinical and scientific work, but also through the institutions, policies, and systems that determine how healthcare is delivered and who is able to access it.",
    ],
    bioFr: [
      "Vianney Tanifor siège au Conseil d'Administration de Gwags Global Impact Institution, où il préside le Comité d'Audit et des Finances. Son parcours s'inscrit dans un engagement plus large envers la médecine, la santé publique, la recherche et les politiques publiques, avec un intérêt particulier pour le renforcement des systèmes de santé et le développement durable au Cameroun. Au sein de Gwags, il a contribué à la gouvernance institutionnelle, aux initiatives de santé, à la mise en œuvre de programmes et à des partenariats visant à élargir les opportunités et à améliorer le bien-être des communautés.",
      "Vianney poursuit des études en sciences biologiques et en sciences politiques à l'Université du Maryland, comté de Baltimore, où ses expériences académiques et de recherche ont approfondi son intérêt pour les liens entre la maladie, la prestation des soins de santé et les politiques qui déterminent l'accès aux soins. Il s'intéresse particulièrement aux maladies neuro-infectieuses et à la manière dont les données scientifiques peuvent contribuer à des systèmes de santé plus solides, de meilleures politiques et des réponses plus efficaces aux défis sanitaires auxquels font face les communautés défavorisées.",
      "Son engagement au sein de Gwags lui a permis de mettre ces intérêts en pratique. Lors d'une importante campagne de santé au Cameroun, il a participé aux soins chirurgicaux, contribué au financement et à la mise en œuvre du projet, et aidé à collecter des données sanitaires actuellement en cours d'analyse pour mieux comprendre les tendances épidémiologiques dans les communautés desservies. À Genève, il a présenté les travaux de Gwags et a été invité à discuter des enjeux de santé au Cameroun. Il a également collaboré avec l'Organisation mondiale de la Santé pour soutenir des ateliers de développement des compétences destinés aux étudiants en médecine au Cameroun.",
      "Vianney aspire à bâtir une carrière à la croisée de la médecine, de la recherche, du service public et des politiques publiques. Ses ambitions à long terme portent sur l'amélioration des résultats en matière de santé, non seulement par le travail clinique et scientifique, mais aussi par les institutions, les politiques et les systèmes qui déterminent comment les soins sont dispensés et qui peut y accéder.",
    ],
    linkedin: 'https://www.linkedin.com/in/vianney-tanifor-9a76b0280/',
    image: '/images/leadership/vianney-tanifor.jpg',
  },
  'noa-winner': {
    name: 'Winner Noa',
    role: 'Board Member',
    roleFr: "Membre du Conseil d'Administration",
    bio: [
      "Winner Noa is a Board Member of Gwags and Chair of the Governance, Regulations and Ethics Committee, where he oversees the organization's governance framework, board composition and effectiveness, ethical standards, and regulatory alignment across the jurisdictions in which Gwags operates. His mandate includes advising the Board on governance and institutional matters, strengthening accountability mechanisms, and ensuring that Gwags' structures and practices remain aligned with applicable requirements and the organization's long-term development.",
      "Beyond Gwags, Winner leads Cross, a strategic advisory practice supporting leaders and organizations across Africa, Europe and the Americas on governance, institutional development, corporate structuring and strategic decision-making. He is also Founder and Editor-in-Chief of Systemic, an independent publication examining the political, economic and social systems shaping contemporary societies, and serves on the board of Fifty Six, a pan-African intellectual think tank dedicated to broadening access to independent thought among young people.",
      "His work sits at the intersection of law, institutional affairs and strategy, supported by a background in management, corporate development and advisory work across public and private-sector environments. This multidisciplinary perspective informs his approach to governance: combining legal and regulatory considerations with an understanding of organizations, markets and institutional dynamics.",
      "Winner holds a Bachelor's degree in Management and is pursuing graduate studies in International Economic Law and Finance in France.",
    ],
    bioFr: [
      "Winner Noa est membre du Conseil d'administration de Gwags et préside le Comité Gouvernance, Réglementation et Éthique. À ce titre, il supervise le cadre de gouvernance de l'institution, la composition et le fonctionnement du Conseil, le respect des normes éthiques ainsi que l'alignement réglementaire de Gwags dans l'ensemble des juridictions où l'institution opère. Son mandat comprend également l'accompagnement du Conseil sur les questions de gouvernance et de développement institutionnel, le renforcement des mécanismes de responsabilité et la consolidation des normes nécessaires au développement international de Gwags.",
      "En parallèle de ses fonctions au sein de Gwags, Winner dirige Cross, un cabinet de conseil stratégique accompagnant des dirigeants et des organisations en Afrique, en Europe et dans les Amériques sur des problématiques de gouvernance, de développement institutionnel, de structuration d'organisations et de prise de décision stratégique. Il est également fondateur et rédacteur en chef de Systemic, une publication indépendante consacrée à l'analyse des systèmes politiques, économiques et sociaux qui façonnent les sociétés contemporaines. Il siège par ailleurs au conseil d'administration de Fifty Six, un think tank intellectuel panafricain consacré à la démocratisation de la pensée indépendante auprès des jeunes.",
      "Son parcours se situe à l'intersection du droit, des affaires institutionnelles et de la stratégie, appuyé par une expérience en management, développement d'entreprises et conseil auprès d'acteurs publics et privés. Cette approche transversale nourrit sa conception de la gouvernance, qui associe les dimensions juridiques et réglementaires à une compréhension des organisations, des marchés et des dynamiques institutionnelles.",
      "Winner est titulaire d'une licence en Management et poursuit une formation de niveau Master en Droit économique international et Finance en France.",
    ],
    linkedin: 'https://www.linkedin.com/in/winnernoa/',
    image: '/images/leadership/winner-noa.jpg',
  },
  'placeholder-executive-director': {
    name: '[Name Placeholder]',
    role: 'Executive Director',
    bio: "The Executive Director oversees the day-to-day operations of Gwags, working closely with the governance board to implement the institution's strategic priorities and ensure program delivery.",
    linkedin: 'https://linkedin.com/in/placeholder', // UPDATE: Replace with actual LinkedIn URL
  },
  'placeholder-director-programs': {
    name: '[Name Placeholder]',
    role: 'Director of Programs',
    bio: "The Director of Programs leads the design, delivery, and evaluation of Gwags's active portfolio of initiatives across education, health, and community development.",
    linkedin: 'https://linkedin.com/in/placeholder', // UPDATE: Replace with actual LinkedIn URL
  },
  'placeholder-director-operations': {
    name: 'Shifu Hammadina',
    role: 'Chief Program Officer',
    roleFr: 'Directeur des Programmes',
    bio: "Shifu leads the design, execution, and evaluation of all Gwags programs, translating the institution's strategy into measurable field impact.",
    bioFr: "Shifu dirige la conception, l'exécution et l'évaluation de l'ensemble des programmes de Gwags, traduisant la stratégie de l'institution en impact mesurable sur le terrain.",
    linkedin: 'https://www.linkedin.com/in/shifu-afayi-h-3708412a3/',
    image: '/images/leadership/shifu-hammadina.jpg',
  },
  'placeholder-director-communications': {
    name: 'Ornella Ebolo',
    role: 'Chief Communications Officer',
    roleFr: 'Directeur de la Communication',
    bio: "The Chief Communications Officer leads Gwags's external engagement, institutional communications, and the development of strategic partnerships.",
    image: '/images/leadership/ornella-ebolo.jpg',
    imagePosition: 'center 16%',
  },
  'gloria-asopjio': {
    name: 'Gloria Asopjio',
    role: 'Founding Member',
    bio: "Gloria led community outreach for the organization's early programs.",
    bioFr: "Gloria a coordonné les relations communautaires pour les premières initiatives de l'organisation.",
    linkedin: 'https://www.linkedin.com/in/gloria-alana-asopjio-060012332/',
    image: '/images/leadership/gloria-asopjio.jpg',
  },
  'alissa-mokem': {
    name: 'Alissa Mokem',
    role: 'Founding Member',
    bio: "Alissa managed the organization's financial operations.",
    bioFr: "Alissa a assuré la gestion financière de l'organisation.",
    image: '/images/leadership/alissa-mokem.jpg',
    imagePosition: 'center 26%',
  },
}
